apiVersion: v1
kind: ConfigMap
metadata:
  name: feast-config
  namespace: lineage
  labels:
    app.kubernetes.io/part-of: feast-kfp-mlflow
data:
  feature_store.yaml: |
    project: customer_churn
    provider: local
    registry:
      registry_type: sql
      path: postgresql://feast:feast@postgres:5432/warehouse
      cache_ttl_seconds: 60

    offline_store:
      type: postgres
      host: postgres
      port: 5432
      database: warehouse
      db_schema: public
      user: feast
      password: feast

    online_store:
      type: redis
      connection_string: redis:6379

    entity_key_serialization_version: 2

    openlineage:
      enabled: true
      transport_type: http
      transport_url: http://marquez
      namespace: churn-demo
      emit_on_apply: true
      emit_on_materialize: true
