apiVersion: batch/v1
kind: Job
metadata:
  name: feast-apply
  namespace: fkm-test
  labels:
    app.kubernetes.io/part-of: feast-kfp-mlflow
    stage: "03-feast-apply"
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        job: feast-apply
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-postgres
          image: registry.access.redhat.com/ubi9:latest
          command:
            - bash
            - -c
            - |
              echo "Waiting for postgres:5432 ..."
              until bash -c "echo > /dev/tcp/postgres/5432" 2>/dev/null; do sleep 2; done
              echo "PostgreSQL is up"
      containers:
        - name: feast-apply
          image: image-registry.openshift-image-registry.svc:5000/fkm-test/fkm-app:latest
          command: ["python3", "-m", "src.feature_store.feast_workflow", "apply"]
          envFrom:
            - configMapRef:
                name: fkm-config
            - secretRef:
                name: fkm-credentials
          volumeMounts:
            - name: feast-config
              mountPath: /app/src/feature_store/feature_store.yaml
              subPath: feature_store.yaml
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: feast-config
          configMap:
            name: feast-config
