---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: lineage
  labels:
    app.kubernetes.io/part-of: feast-kfp-mlflow
    app.kubernetes.io/component: postgres
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
