---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: lineage
  labels:
    app: redis
    app.kubernetes.io/part-of: feast-kfp-mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: quay.io/sclorg/redis-7-c9s:latest
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - redis-cli ping | grep -q PONG
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - redis-cli ping | grep -q PONG
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: lineage
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
