---
# Expose the FastAPI inference API externally
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: inference-api
  namespace: lineage
  labels:
    app: inference-api
    app.kubernetes.io/part-of: feast-kfp-mlflow
spec:
  to:
    kind: Service
    name: inference-api
  port:
    targetPort: 8000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

---
# Expose the MLflow UI externally
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mlflow-server
  namespace: lineage
  labels:
    app: mlflow-server
    app.kubernetes.io/part-of: feast-kfp-mlflow
spec:
  to:
    kind: Service
    name: mlflow-server
  port:
    targetPort: 5000

---
# Expose MinIO console externally
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mlflow-minio-console
  namespace: lineage
  labels:
    app: mlflow-minio
    app.kubernetes.io/part-of: feast-kfp-mlflow
spec:
  to:
    kind: Service
    name: mlflow-minio
  port:
    targetPort: 9001

---
# Expose Marquez API externally
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: marquez
  namespace: lineage
  labels:
    app.kubernetes.io/component: marquez
    app.kubernetes.io/part-of: feast-kfp-mlflow
spec:
  to:
    kind: Service
    name: marquez
  port:
    targetPort: http

---
# Expose Marquez Web UI externally
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: marquez-web
  namespace: lineage
  labels:
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: feast-kfp-mlflow
spec:
  to:
    kind: Service
    name: marquez-web
  port:
    targetPort: http
