---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: lineage-operator
  namespace: lineage-operator-system
  labels:
    app: lineage-operator

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: lineage-operator
  namespace: lineage-operator-system
  labels:
    app: lineage-operator
spec:
  output:
    to:
      kind: ImageStreamTag
      name: lineage-operator:latest
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers:
    - type: ConfigChange
  runPolicy: Serial
