apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: dspa
  namespace: lineage
  labels:
    app.kubernetes.io/part-of: feast-kfp-mlflow
spec:
  dspVersion: v2

  apiServer:
    deploy: true
    cacheEnabled: true
    enableOauth: true
    enableSamplePipeline: false
    pipelineStore: kubernetes
    artifactSignedURLExpirySeconds: 60

  database:
    disableHealthCheck: false
    mariaDB:
      deploy: true
      pipelineDBName: mlpipeline
      pvcSize: 10Gi
      username: mlpipeline

  objectStorage:
    disableHealthCheck: false
    enableExternalRoute: false
    externalStorage:
      basePath: ""
      bucket: pipeline-artifacts
      host: mlflow-minio.lineage.svc:9000
      port: ""
      region: us-east-1
      scheme: http
      s3CredentialsSecret:
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
        secretName: dashboard-dspa-secret

  persistenceAgent:
    deploy: true
    numWorkers: 2

  podToPodTLS: true

  scheduledWorkflow:
    cronScheduleTimezone: UTC
    deploy: true
