apiVersion: v1
kind: Secret
metadata:
  name: dashboard-dspa-secret
  namespace: lineage
  labels:
    app.kubernetes.io/part-of: feast-kfp-mlflow
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "minioadmin123"
