//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCapabilities) DeepCopyInto(out *AgentCapabilities) {
	*out = *in
	if in.Streaming != nil {
		in, out := &in.Streaming, &out.Streaming
		*out = new(bool)
		**out = **in
	}
	if in.PushNotifications != nil {
		in, out := &in.PushNotifications, &out.PushNotifications
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCapabilities.
func (in *AgentCapabilities) DeepCopy() *AgentCapabilities {
	if in == nil {
		return nil
	}
	out := new(AgentCapabilities)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCard) DeepCopyInto(out *AgentCard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCard.
func (in *AgentCard) DeepCopy() *AgentCard {
	if in == nil {
		return nil
	}
	out := new(AgentCard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentCard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCardData) DeepCopyInto(out *AgentCardData) {
	*out = *in
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(AgentProvider)
		**out = **in
	}
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = new(AgentCapabilities)
		(*in).DeepCopyInto(*out)
	}
	if in.Skills != nil {
		in, out := &in.Skills, &out.Skills
		*out = make([]AgentSkill, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DataLineage != nil {
		in, out := &in.DataLineage, &out.DataLineage
		*out = new(DataLineage)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCardData.
func (in *AgentCardData) DeepCopy() *AgentCardData {
	if in == nil {
		return nil
	}
	out := new(AgentCardData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCardList) DeepCopyInto(out *AgentCardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentCard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCardList.
func (in *AgentCardList) DeepCopy() *AgentCardList {
	if in == nil {
		return nil
	}
	out := new(AgentCardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentCardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCardSpec) DeepCopyInto(out *AgentCardSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCardSpec.
func (in *AgentCardSpec) DeepCopy() *AgentCardSpec {
	if in == nil {
		return nil
	}
	out := new(AgentCardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentCardStatus) DeepCopyInto(out *AgentCardStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Card != nil {
		in, out := &in.Card, &out.Card
		*out = new(AgentCardData)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentCardStatus.
func (in *AgentCardStatus) DeepCopy() *AgentCardStatus {
	if in == nil {
		return nil
	}
	out := new(AgentCardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentProvider) DeepCopyInto(out *AgentProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentProvider.
func (in *AgentProvider) DeepCopy() *AgentProvider {
	if in == nil {
		return nil
	}
	out := new(AgentProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSkill) DeepCopyInto(out *AgentSkill) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InputModes != nil {
		in, out := &in.InputModes, &out.InputModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OutputModes != nil {
		in, out := &in.OutputModes, &out.OutputModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSkill.
func (in *AgentSkill) DeepCopy() *AgentSkill {
	if in == nil {
		return nil
	}
	out := new(AgentSkill)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataLineage) DeepCopyInto(out *DataLineage) {
	*out = *in
	if in.Dataset != nil {
		in, out := &in.Dataset, &out.Dataset
		*out = new(LineageDataset)
		**out = **in
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(LineageDataset)
		**out = **in
	}
	if in.Transformations != nil {
		in, out := &in.Transformations, &out.Transformations
		*out = make([]Transformation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Summary != nil {
		in, out := &in.Summary, &out.Summary
		*out = new(LineageSummary)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataLineage.
func (in *DataLineage) DeepCopy() *DataLineage {
	if in == nil {
		return nil
	}
	out := new(DataLineage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LineageDataset) DeepCopyInto(out *LineageDataset) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LineageDataset.
func (in *LineageDataset) DeepCopy() *LineageDataset {
	if in == nil {
		return nil
	}
	out := new(LineageDataset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LineageJob) DeepCopyInto(out *LineageJob) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LineageJob.
func (in *LineageJob) DeepCopy() *LineageJob {
	if in == nil {
		return nil
	}
	out := new(LineageJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LineageSummary) DeepCopyInto(out *LineageSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LineageSummary.
func (in *LineageSummary) DeepCopy() *LineageSummary {
	if in == nil {
		return nil
	}
	out := new(LineageSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Transformation) DeepCopyInto(out *Transformation) {
	*out = *in
	if in.InputDataset != nil {
		in, out := &in.InputDataset, &out.InputDataset
		*out = new(LineageDataset)
		**out = **in
	}
	if in.Job != nil {
		in, out := &in.Job, &out.Job
		*out = new(LineageJob)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Transformation.
func (in *Transformation) DeepCopy() *Transformation {
	if in == nil {
		return nil
	}
	out := new(Transformation)
	in.DeepCopyInto(out)
	return out
}
